version: '3.8'

name: reiverr-prod

services:
  reiverr:
    image: ghcr.io/aleksilassila/reiverr:latest
    container_name: reiverr-prod
    build:
      context: .
      target: production
    ports:
      - 9494:9494
